version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=hassantest232412414fgdfg!
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - app_network

  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=Ecommerce;User=sa;Password=hassantest232412414fgdfg!;Encrypt=False;Connection Timeout=30;
    depends_on:
      - sqlserver
    networks:
      - app_network

volumes:
  sqlserver_data:

networks:
  app_network:
    driver: bridge
